# Generated by Django 3.1.7 on 2021-02-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('market', models.CharField(max_length=10)),
                ('code_name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('chart_data_json', models.CharField(max_length=50)),
                ('buy_price', models.FloatField()),
                ('buy_date', models.DateField()),
                ('buy_memo', models.TextField()),
                ('sell_price', models.FloatField()),
                ('sell_date', models.DateField()),
                ('sell_memo', models.TextField()),
                ('to_sell_price', models.FloatField()),
                ('to_sell_datee', models.DateField()),
                ('to_buy_price', models.FloatField()),
                ('to_buy_datee', models.DateField()),
            ],
        ),
    ]
