# Generated by Django 3.1.7 on 2021-02-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='to_buy_datee',
        ),
        migrations.RemoveField(
            model_name='post',
            name='to_sell_datee',
        ),
        migrations.AddField(
            model_name='post',
            name='to_buy_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='to_sell_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='buy_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='buy_memo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='buy_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='chart_data_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sell_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sell_memo',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sell_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='to_buy_price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='to_sell_price',
            field=models.FloatField(null=True),
        ),
    ]
